services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  odoo:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
    command: [
      "--database=odoo_hr",
      "--db_host=db",
      "--db_port=5432",
      "--db_user=odoo",
      "--db_password=odoo",
      "--xmlrpc-port=8069",
      "--dev=reload"
    ]

volumes:
  odoo-web-data:
  odoo-db-data:
